name: Style

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: pull submodule
      run: git submodule update --init --recursive
    
    - name: Install clang-format
      run: brew install clang-format

    - name: configure
      run: cmake -Htest -Bbuild

    - name: check style
      run: cmake --build build --target check-format 
